### ISSUE TITLE
Directions on where to put Data.rsdk unclear

### ISSUE THREAD

**Issue by SirYodaJedi** [ultra0000/Sonic-CD-11-Decompilation#1]
When booting up the software, a screen appears that says to either press B for 16:9 or press home to exit (It might also say press A for 4:3, but I can't disable overscan at SD res on my TV). Pressing either A or B results in the application closing and returning to the homebrew menu. 
I am using `patch.56.com.sega.soniccd.classic.obb`, renamed to `data.rsdk`, as per the main fork. I do not have the PC version of the data.rsdk available to test.
Pictures:
![IMG_5704](https://user-images.githubusercontent.com/50331474/156883870-dad13943-e6db-40b5-8ad6-21de76ae378d.jpg)
![IMG_5705](https://user-images.githubusercontent.com/50331474/156883876-1130cc0d-5e9c-4241-8cd8-924691bcf430.jpg)

**Comment by octobepis** [comment]
same issue, using PC rsdk

**Comment by mahougomi** [comment]
same issue with Steam rsdk. has anyone gotten this working?

[edit] nevermind, i did a bit of looking around on the gbatemp thread for this and it looks like you need to put Data.rsdk in a SonicCD folder in the *root* of the device being used, not the one in the apps folder

**Comment by SirYodaJedi** [comment]
> it looks like you need to put Data.rsdk in a SonicCD folder in the root of the device being used, not the one in the apps folder

Just tested with version from Steam; that worked.

**Comment by SuperSonic1528** [comment]
Quick Note:You Need To Copy The SonicCD Folder In Apps AND The Root, If You Only Put It In The Root, Homebrew Channel Will Not Detect It.

**Comment by SirYodaJedi** [comment]
> Quick Note:You Need To Copy The SonicCD Folder In Apps AND The Root, If You Only Put It In The Root, Homebrew Channel Will Not Detect It.

Actually, there should be two separate `SonicCD` folders. One should be at `USB1:/SonicCD` or `SD:/SonicCD`, and the other should be in `USB1:/apps/SonicCD` or `SD:/apps/SonicCD` (both folders should be on the same device). The folder at the root should have the data.rdsk, and the folder in the apps directory should have the executable and stuff from this release.
